const $=id=>document.getElementById(id);
const RULES=[
{id:'ppe_eye',title:'Protección ocular no visible',icon:'🥽',severity:'Alto',type:'Acto inseguro',norm:'Ley 19.587 arts. 8(c) y 10(a); Decreto 351/79, Cap. 19 (arts. 188–190).',action:'Detener o revisar la tarea cuando exista riesgo para los ojos; verificar EPP requerido, adecuación al riesgo y uso efectivo.'},
{id:'ppe_head',title:'Casco no visible donde sería requerido',icon:'⛑️',severity:'Alto',type:'Acto inseguro',norm:'Ley 19.587 arts. 8(c) y 10(a); Decreto 351/79, Cap. 19.',action:'Verificar evaluación de riesgos y obligatoriedad de protección de cabeza para la tarea/sector.'},
{id:'fire_obstructed',title:'Matafuego / acceso de extinción obstruido',icon:'🧯',severity:'Alto',type:'Condición insegura',norm:'Decreto 351/79 arts. 160 y 176; Anexo VII.',action:'Liberar el acceso, verificar señalización, ubicación, distancia de recorrido y condiciones del equipo.'},
{id:'electric_open',title:'Tablero / partes eléctricas accesibles',icon:'⚡',severity:'Alto',type:'Condición insegura',norm:'Ley 19.587 arts. 7(c), 8 y 9(d); Decreto 351/79 Anexo VI.',action:'Restringir acceso y verificar envolvente, aislamiento, señalización y condición segura de la instalación.'},
{id:'walkway_obstruction',title:'Obstáculo / cable en circulación',icon:'🚧',severity:'Medio',type:'Condición insegura',norm:'Ley 19.587 arts. 8 y 9(e); Decreto 351/79 art. 42; art. 110 para herramientas en zonas de paso.',action:'Retirar, proteger o canalizar el obstáculo y conservar libre la zona de tránsito.'},
{id:'machine_guard',title:'Máquina / herramienta sin resguardo visible',icon:'⚙️',severity:'Alto',type:'Condición insegura',norm:'Decreto 351/79 arts. 103, 106, 107 y 113.',action:'No operar hasta verificar resguardos, pantallas, protecciones y dispositivos de seguridad adecuados.'},
{id:'unsafe_tool',title:'Uso inseguro de herramienta portátil',icon:'🛠️',severity:'Alto',type:'Acto inseguro',norm:'Ley 19.587 art. 10(a); Decreto 351/79 arts. 110, 111 y 113.',action:'Revisar herramienta, método de trabajo, capacitación, protección contra proyecciones y EPP.'},
{id:'height',title:'Trabajo en altura sin protección visible',icon:'🪜',severity:'Alto',type:'Acto inseguro',norm:'Decreto 351/79 art. 200 y requisitos aplicables según tarea/sector.',action:'Interrumpir y verificar sistema de protección contra caídas, anclaje, acceso y procedimiento seguro.'},
{id:'storage',title:'Acopio / almacenamiento inestable',icon:'📦',severity:'Medio',type:'Condición insegura',norm:'Ley 19.587 arts. 7 y 8; Decreto 351/79 art. 42 y requisitos específicos según material.',action:'Reordenar el almacenamiento y verificar estabilidad, altura, separación de circulaciones y riesgo de caída de objetos.'},
{id:'spill',title:'Derrame / piso con riesgo de caída',icon:'💧',severity:'Medio',type:'Condición insegura',norm:'Ley 19.587 arts. 8 y 9(e); Decreto 351/79 art. 42.',action:'Señalizar, aislar y limpiar; identificar y controlar la fuente del derrame.'},
{id:'ergonomics',title:'Manipulación / postura potencialmente riesgosa',icon:'🏋️',severity:'Medio',type:'Acto inseguro',norm:'Resolución MTEySS 295/2003, Anexo I.',action:'Evaluar peso, frecuencia, alcance, postura, duración y condiciones reales antes de concluir incumplimiento.'},
{id:'vehicle_person',title:'Interacción persona–vehículo',icon:'🚜',severity:'Alto',type:'Condición insegura',norm:'Ley 19.587 arts. 8 y 9; para autoelevadores: Resolución SRT 960/2015.',action:'Separar circulación peatonal/vehicular, controlar velocidad, visibilidad, señalización y condiciones de operación.'},
{id:'exit_blocked',title:'Salida / vía de escape obstruida',icon:'🚪',severity:'Alto',type:'Condición insegura',norm:'Decreto 351/79 art. 160 y Anexo VII.',action:'Liberar inmediatamente la trayectoria y verificar señalización, iluminación y condiciones del medio de escape.'}
];
let stream=null,model=null,running=false,facing='environment',lastCapture=null,pendingRule=null,lastAutoAt=0;
let findings=JSON.parse(localStorage.getItem('sst_findings_v1')||'[]');
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function renderRules(){ $('ruleList').innerHTML=RULES.map(r=>`<div class="rule" data-rule="${r.id}"><div class="ico">${r.icon}</div><div><strong>${r.title}</strong><small>${r.severity} · ${r.norm}</small></div></div>`).join(''); document.querySelectorAll('.rule').forEach(el=>el.onclick=()=>openRule(el.dataset.rule)); }
function openRule(id){pendingRule=RULES.find(r=>r.id===id); if(!pendingRule)return; $('mTitle').textContent=pendingRule.title; $('mNorm').textContent='Referencia: '+pendingRule.norm+' — posible incumplimiento sujeto a validación.'; $('mType').value=pendingRule.type; $('mAction').value=pendingRule.action; $('mNotes').value=''; $('modal').classList.add('show');}
function saveFinding(){if(!pendingRule)return; findings.unshift({id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),ruleId:pendingRule.id,title:pendingRule.title,severity:pendingRule.severity,type:$('mType').value,norm:pendingRule.norm,sector:$('mSector').value.trim(),notes:$('mNotes').value.trim(),action:$('mAction').value.trim(),time:new Date().toISOString(),source:'manual/guiado',image:lastCapture}); localStorage.setItem('sst_findings_v1',JSON.stringify(findings)); $('modal').classList.remove('show'); renderFindings();}
function renderFindings(){ $('totalCount').textContent=findings.length; $('highCount').textContent=findings.filter(f=>f.severity==='Alto').length; $('autoCount').textContent=findings.filter(f=>f.source==='automático').length; $('findings').innerHTML=findings.length?findings.map(f=>`<div class="finding"><div class="finding-top"><div><h3>${esc(f.title)}</h3><p>${esc(f.sector||'Sector no indicado')} · ${new Date(f.time).toLocaleString()}</p></div><span class="tag ${f.severity==='Alto'?'red':f.severity==='Medio'?'amber':''}">${f.severity}</span></div><p><b>${esc(f.type)}</b> · ${esc(f.source)}</p><p>${esc(f.notes||'Sin observación adicional.')}</p><p><b>Norma relacionada:</b> ${esc(f.norm)}</p><p><b>Acción:</b> ${esc(f.action)}</p>${f.image?`<img class="thumb" src="${f.image}" alt="Evidencia">`:''}</div>`).join(''):'<div class="status">Todavía no hay hallazgos registrados.</div>';}
async function startCamera(){try{stopCamera(); stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}},audio:false}); $('video').srcObject=stream; await $('video').play(); $('placeholder').style.display='none'; $('onlinePill').textContent='● cámara activa'; $('onlinePill').classList.add('on'); $('startBtn').disabled=true;$('stopBtn').disabled=false;$('captureBtn').disabled=false;$('switchBtn').disabled=false; running=true; resizeCanvas(); if(!model)loadModel(); detectLoop();}catch(e){$('status').textContent='No se pudo abrir la cámara. La web debe ejecutarse por HTTPS (o localhost) y tener permiso de cámara. '+e.message;}}
function stopCamera(){running=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}$('video').srcObject=null;$('placeholder').style.display='grid';$('onlinePill').textContent='● cámara inactiva';$('onlinePill').classList.remove('on');$('startBtn').disabled=false;$('stopBtn').disabled=true;$('captureBtn').disabled=true;$('switchBtn').disabled=true;const c=$('overlay');c.getContext('2d').clearRect(0,0,c.width,c.height);}
async function loadModel(){try{$('modelStatus').textContent='IA general: cargando…';model=await cocoSsd.load({base:'lite_mobilenet_v2'});$('modelStatus').textContent='IA general: activa';}catch(e){$('modelStatus').textContent='IA general: error';$('status').textContent='La cámara funciona, pero el detector general no pudo cargarse. Podés seguir registrando hallazgos.';}}
function resizeCanvas(){const v=$('video'),c=$('overlay');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;}
function draw(preds){const c=$('overlay'),ctx=c.getContext('2d'),v=$('video');if(c.width!==v.videoWidth&&v.videoWidth)resizeCanvas();ctx.clearRect(0,0,c.width,c.height);ctx.lineWidth=4;ctx.font='20px system-ui';preds.forEach(p=>{const[x,y,w,h]=p.bbox;ctx.strokeStyle='#23b7d9';ctx.fillStyle='rgba(3,10,18,.78)';ctx.strokeRect(x,y,w,h);const label=`${p.class} ${(p.score*100).toFixed(0)}%`,tw=ctx.measureText(label).width+14;ctx.fillRect(x,Math.max(0,y-28),tw,28);ctx.fillStyle='#fff';ctx.fillText(label,x+7,Math.max(20,y-7));});}
function near(a,b){const ac=[a[0]+a[2]/2,a[1]+a[3]/2],bc=[b[0]+b[2]/2,b[1]+b[3]/2];return Math.hypot(ac[0]-bc[0],ac[1]-bc[1])<Math.max(a[2],a[3],b[2],b[3])*1.4;}
function maybeAuto(preds){const people=preds.filter(p=>p.class==='person'&&p.score>.55),veh=preds.filter(p=>['car','truck','bus','motorcycle'].includes(p.class)&&p.score>.45);if(!people.length||!veh.length)return;const now=Date.now();if(now-lastAutoAt<7000)return;if(people.some(a=>veh.some(b=>near(a.bbox,b.bbox)))){lastAutoAt=now;$('autoAlert').style.display='block';$('autoAlert').textContent='⚠️ IA: persona y vehículo detectados próximos. Revisar interacción peatón–vehículo. No implica incumplimiento confirmado.';}}
async function detectLoop(){if(!running)return;if(model&&$('video').readyState>=2){try{const p=await model.detect($('video'),20,.42);$('fpsStatus').textContent=`${p.length} det.`;draw(p);maybeAuto(p);}catch(e){}}setTimeout(()=>requestAnimationFrame(detectLoop),350);}
function capture(){const v=$('video');if(!v.videoWidth)return;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);lastCapture=c.toDataURL('image/jpeg',.75);$('status').textContent='Evidencia capturada. Elegí ahora el tipo de condición/acto para registrarla.';}
function exportJSON(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),version:'SST IA V1',findings},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sst-ia-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
$('startBtn').onclick=startCamera;$('stopBtn').onclick=stopCamera;$('captureBtn').onclick=capture;$('switchBtn').onclick=async()=>{facing=facing==='environment'?'user':'environment';await startCamera();};$('cancelModal').onclick=()=>$('modal').classList.remove('show');$('saveFinding').onclick=saveFinding;$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('show');};$('exportBtn').onclick=exportJSON;$('clearBtn').onclick=()=>{if(confirm('¿Borrar todos los hallazgos?')){findings=[];lastCapture=null;localStorage.setItem('sst_findings_v1','[]');renderFindings();}};window.addEventListener('resize',resizeCanvas);renderRules();renderFindings();
